# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../ffigen_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FFIgenTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FFIgenTest

  install_all_flutter_pods(flutter_application_path)
  pod 'SwiftUIIntrospect'

  target 'FFIgenTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FFIgenTestUITests' do
    # Pods for testing
  end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end

end
